### ISSUE TITLE
Problem with the example code

### ISSUE THREAD

**Issue by johnareid54** [IVLIVS-III/ivlivs_pdf_viewer#1]
I can't get the example version to run The code is stopping at the await - here is my version:

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:ivlivs_pdf_viewer/ivlivs_pdf_viewer.dart';

class MyWidget extends StatefulWidget {
  const MyWidget({super.key});

  @override
  State<MyWidget> createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  String sourceName = "tester.pdf";
   Uint8List data = ( await rootBundle.load("tester.pdf")).buffer.asUint8List();


  @override
  Widget build(BuildContext context) {
    return PdfViewer(
      sourceName: sourceName,
      data: data,
    );
  }
}
```

I am getting a bug on the Uint8List data line: 

	"code": "await_in_wrong_context",
	"severity": 8,
	"message": "The await expression can only be used in an async function.\nTry marking the function body with either 'async' or 'async*'.",

**Comment by IVLIVS-III** [comment]
You can use `await` [only in an `async` function](https://dart.dev/libraries/async/async-await#working-with-futures-async-and-await). However, you try to use `await` directly inside the `_MyWidgetState` class.

To fix this, you could use the [`FuturePdfViewer`](https://pub.dev/documentation/ivlivs_pdf_viewer/latest/ivlivs_pdf_viewer/FuturePdfViewer-class.html) class like so:

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:ivlivs_pdf_viewer/ivlivs_pdf_viewer.dart';

class MyWidget extends StatefulWidget {
  const MyWidget({super.key});

  @override
  State<MyWidget> createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  String sourceName = "tester.pdf";
  Future<Uint8List> dataFuture = rootBundle.load("tester.pdf").then((data) => data.buffer.asUint8List());


  @override
  Widget build(BuildContext context) {
    return FuturePdfViewer(
      sourceName: sourceName,
      future: dataFuture,
    );
  }
}
```

**Comment by johnareid54** [comment]
Many thanks it work well!

**Comment by johnareid54** [comment]
Closed

**Comment by johnareid54** [comment]
The pdf viewer is working fine and is easy to use. It would be even easier if all you had to do was supply the file path & name and package could do the rootBundle.load.
